export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const SHOW_CART = "SHOW_CART";
export const HIDE_CART = "HIDE_CART";
export const CURRENCY_CHANGE = "CURRENCY_CHANGE";
